
default: run

TARGET = run
SRCS = main.cpp
CXX = g++
#CXX = clang
CXXFLAGS = -std=c++14 -Irange-v3/include

ranges:
	git clone https://github.com/ericniebler/range-v3



$(TARGET): main.o
	$(CXX) -o $(TARGET) $(CFXXLAGS) main.o

depend:
	makedepend -- $(CXXFLAGS) -- $(SRCS)


# DO NOT DELETE

main.o: range-v3/include/range/v3/all.hpp range-v3/include/range/v3/core.hpp
main.o: range-v3/include/range/v3/begin_end.hpp
main.o: range-v3/include/range/v3/range_fwd.hpp
main.o: range-v3/include/meta/meta.hpp range-v3/include/meta/meta_fwd.hpp
main.o: range-v3/include/range/v3/detail/config.hpp
main.o: range-v3/include/range/v3/utility/static_const.hpp
main.o: range-v3/include/range/v3/utility/dangling.hpp
main.o: range-v3/include/range/v3/utility/tagged_pair.hpp
main.o: range-v3/include/range/v3/utility/concepts.hpp
main.o: range-v3/include/range/v3/utility/swap.hpp
main.o: range-v3/include/range/v3/utility/move.hpp
main.o: range-v3/include/range/v3/utility/associated_types.hpp
main.o: range-v3/include/range/v3/utility/nullptr_v.hpp
main.o: range-v3/include/range/v3/utility/common_type.hpp
main.o: range-v3/include/range/v3/utility/iterator.hpp
main.o: range-v3/include/range/v3/utility/iterator_traits.hpp
main.o: range-v3/include/range/v3/utility/iterator_concepts.hpp
main.o: range-v3/include/range/v3/utility/functional.hpp
main.o: range-v3/include/range/v3/utility/box.hpp
main.o: range-v3/include/range/v3/utility/get.hpp
main.o: range-v3/include/range/v3/utility/invoke.hpp
main.o: range-v3/include/range/v3/utility/compressed_pair.hpp
main.o: range-v3/include/range/v3/utility/basic_iterator.hpp
main.o: range-v3/include/range/v3/range_access.hpp
main.o: range-v3/include/range/v3/utility/semiregular.hpp
main.o: range-v3/include/range/v3/detail/optional.hpp
main.o: range-v3/include/range/v3/detail/variant.hpp
main.o: range-v3/include/range/v3/distance.hpp
main.o: range-v3/include/range/v3/size.hpp
main.o: range-v3/include/range/v3/range_traits.hpp
main.o: range-v3/include/range/v3/range_concepts.hpp
main.o: range-v3/include/range/v3/data.hpp
main.o: range-v3/include/range/v3/empty.hpp
main.o: range-v3/include/range/v3/view_facade.hpp
main.o: range-v3/include/range/v3/view_interface.hpp
main.o: range-v3/include/range/v3/to_container.hpp
main.o: range-v3/include/range/v3/action/concepts.hpp
main.o: range-v3/include/range/v3/utility/common_iterator.hpp
main.o: range-v3/include/range/v3/utility/common_tuple.hpp
main.o: range-v3/include/range/v3/utility/tuple_algorithm.hpp
main.o: range-v3/include/range/v3/view_adaptor.hpp
main.o: range-v3/include/range/v3/view/all.hpp
main.o: range-v3/include/range/v3/iterator_range.hpp
main.o: range-v3/include/range/v3/algorithm/tagspec.hpp
main.o: range-v3/include/range/v3/range_for.hpp
main.o: range-v3/include/range/v3/at.hpp range-v3/include/range/v3/back.hpp
main.o: range-v3/include/range/v3/front.hpp
main.o: range-v3/include/range/v3/istream_range.hpp
main.o: range-v3/include/range/v3/getlines.hpp
main.o: range-v3/include/range/v3/algorithm.hpp
main.o: range-v3/include/range/v3/algorithm/adjacent_find.hpp
main.o: range-v3/include/range/v3/algorithm/all_of.hpp
main.o: range-v3/include/range/v3/algorithm/any_of.hpp
main.o: range-v3/include/range/v3/algorithm/binary_search.hpp
main.o: range-v3/include/range/v3/algorithm/lower_bound.hpp
main.o: range-v3/include/range/v3/algorithm/partition_point.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/partition_point_n.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/lower_bound_n.hpp
main.o: range-v3/include/range/v3/algorithm/copy.hpp
main.o: range-v3/include/range/v3/utility/copy.hpp
main.o: range-v3/include/range/v3/algorithm/copy_backward.hpp
main.o: range-v3/include/range/v3/algorithm/copy_if.hpp
main.o: range-v3/include/range/v3/algorithm/copy_n.hpp
main.o: range-v3/include/range/v3/algorithm/count.hpp
main.o: range-v3/include/range/v3/algorithm/count_if.hpp
main.o: range-v3/include/range/v3/algorithm/equal.hpp
main.o: range-v3/include/range/v3/algorithm/equal_range.hpp
main.o: range-v3/include/range/v3/algorithm/upper_bound.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/upper_bound_n.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/equal_range_n.hpp
main.o: range-v3/include/range/v3/algorithm/fill.hpp
main.o: range-v3/include/range/v3/algorithm/fill_n.hpp
main.o: range-v3/include/range/v3/algorithm/find.hpp
main.o: range-v3/include/range/v3/algorithm/find_end.hpp
main.o: range-v3/include/range/v3/algorithm/find_first_of.hpp
main.o: range-v3/include/range/v3/algorithm/find_if.hpp
main.o: range-v3/include/range/v3/algorithm/find_if_not.hpp
main.o: range-v3/include/range/v3/algorithm/for_each.hpp
main.o: range-v3/include/range/v3/algorithm/generate.hpp
main.o: range-v3/include/range/v3/algorithm/generate_n.hpp
main.o: range-v3/include/range/v3/algorithm/heap_algorithm.hpp
main.o: range-v3/include/range/v3/algorithm/inplace_merge.hpp
main.o: range-v3/include/range/v3/utility/memory.hpp
main.o: range-v3/include/range/v3/utility/counted_iterator.hpp
main.o: range-v3/include/range/v3/algorithm/min.hpp
main.o: range-v3/include/range/v3/algorithm/move.hpp
main.o: range-v3/include/range/v3/algorithm/merge.hpp
main.o: range-v3/include/range/v3/utility/tagged_tuple.hpp
main.o: range-v3/include/range/v3/algorithm/rotate.hpp
main.o: range-v3/include/range/v3/algorithm/move_backward.hpp
main.o: range-v3/include/range/v3/algorithm/swap_ranges.hpp
main.o: range-v3/include/range/v3/algorithm/is_partitioned.hpp
main.o: range-v3/include/range/v3/algorithm/is_sorted.hpp
main.o: range-v3/include/range/v3/algorithm/is_sorted_until.hpp
main.o: range-v3/include/range/v3/algorithm/lexicographical_compare.hpp
main.o: range-v3/include/range/v3/algorithm/max.hpp
main.o: range-v3/include/range/v3/algorithm/max_element.hpp
main.o: range-v3/include/range/v3/algorithm/min_element.hpp
main.o: range-v3/include/range/v3/algorithm/minmax.hpp
main.o: range-v3/include/range/v3/algorithm/minmax_element.hpp
main.o: range-v3/include/range/v3/algorithm/mismatch.hpp
main.o: range-v3/include/range/v3/algorithm/none_of.hpp
main.o: range-v3/include/range/v3/algorithm/nth_element.hpp
main.o: range-v3/include/range/v3/algorithm/partial_sort.hpp
main.o: range-v3/include/range/v3/algorithm/partial_sort_copy.hpp
main.o: range-v3/include/range/v3/algorithm/partition.hpp
main.o: range-v3/include/range/v3/algorithm/partition_copy.hpp
main.o: range-v3/include/range/v3/algorithm/permutation.hpp
main.o: range-v3/include/range/v3/algorithm/reverse.hpp
main.o: range-v3/include/range/v3/algorithm/remove.hpp
main.o: range-v3/include/range/v3/algorithm/remove_copy.hpp
main.o: range-v3/include/range/v3/algorithm/remove_copy_if.hpp
main.o: range-v3/include/range/v3/algorithm/remove_if.hpp
main.o: range-v3/include/range/v3/algorithm/replace.hpp
main.o: range-v3/include/range/v3/algorithm/replace_copy.hpp
main.o: range-v3/include/range/v3/algorithm/replace_copy_if.hpp
main.o: range-v3/include/range/v3/algorithm/replace_if.hpp
main.o: range-v3/include/range/v3/algorithm/reverse_copy.hpp
main.o: range-v3/include/range/v3/algorithm/rotate_copy.hpp
main.o: range-v3/include/range/v3/algorithm/sample.hpp
main.o: range-v3/include/range/v3/utility/random.hpp
main.o: range-v3/include/range/v3/algorithm/search.hpp
main.o: range-v3/include/range/v3/algorithm/search_n.hpp
main.o: range-v3/include/range/v3/algorithm/set_algorithm.hpp
main.o: range-v3/include/range/v3/algorithm/shuffle.hpp
main.o: range-v3/include/range/v3/algorithm/sort.hpp
main.o: range-v3/include/range/v3/algorithm/stable_partition.hpp
main.o: range-v3/include/range/v3/algorithm/stable_sort.hpp
main.o: range-v3/include/range/v3/algorithm/transform.hpp
main.o: range-v3/include/range/v3/utility/unreachable.hpp
main.o: range-v3/include/range/v3/algorithm/unique.hpp
main.o: range-v3/include/range/v3/algorithm/unique_copy.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/merge_n.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/merge_n_with_buffer.hpp
main.o: range-v3/include/range/v3/algorithm/aux_/sort_n_with_buffer.hpp
main.o: range-v3/include/range/v3/action.hpp
main.o: range-v3/include/range/v3/action/drop.hpp
main.o: range-v3/include/range/v3/action/action.hpp
main.o: range-v3/include/range/v3/action/erase.hpp
main.o: range-v3/include/range/v3/action/insert.hpp
main.o: range-v3/include/range/v3/action/drop_while.hpp
main.o: range-v3/include/range/v3/action/join.hpp
main.o: range-v3/include/range/v3/action/push_back.hpp
main.o: range-v3/include/range/v3/action/push_front.hpp
main.o: range-v3/include/range/v3/action/remove_if.hpp
main.o: range-v3/include/range/v3/action/shuffle.hpp
main.o: range-v3/include/range/v3/action/slice.hpp
main.o: range-v3/include/range/v3/action/sort.hpp
main.o: range-v3/include/range/v3/action/split.hpp
main.o: range-v3/include/range/v3/view/split.hpp
main.o: range-v3/include/range/v3/detail/satisfy_boost_range.hpp
main.o: range-v3/include/range/v3/view/view.hpp
main.o: range-v3/include/range/v3/view/iota.hpp
main.o: range-v3/include/range/v3/view/take_exactly.hpp
main.o: range-v3/include/range/v3/view/counted.hpp
main.o: range-v3/include/range/v3/view/delimit.hpp
main.o: range-v3/include/range/v3/view/indirect.hpp
main.o: range-v3/include/range/v3/view/take_while.hpp
main.o: range-v3/include/range/v3/view/transform.hpp
main.o: range-v3/include/range/v3/action/stable_sort.hpp
main.o: range-v3/include/range/v3/action/stride.hpp
main.o: range-v3/include/range/v3/action/take.hpp
main.o: range-v3/include/range/v3/action/take_while.hpp
main.o: range-v3/include/range/v3/action/transform.hpp
main.o: range-v3/include/range/v3/action/unique.hpp
main.o: range-v3/include/range/v3/numeric.hpp
main.o: range-v3/include/range/v3/numeric/accumulate.hpp
main.o: range-v3/include/range/v3/numeric/adjacent_difference.hpp
main.o: range-v3/include/range/v3/numeric/iota.hpp
main.o: range-v3/include/range/v3/numeric/inner_product.hpp
main.o: range-v3/include/range/v3/numeric/partial_sum.hpp
main.o: range-v3/include/range/v3/view.hpp
main.o: range-v3/include/range/v3/view/adjacent_remove_if.hpp
main.o: range-v3/include/range/v3/view/adjacent_filter.hpp
main.o: range-v3/include/range/v3/utility/optional.hpp
main.o: range-v3/include/range/v3/utility/variant.hpp
main.o: range-v3/include/range/v3/view/any_view.hpp
main.o: range-v3/include/range/v3/utility/polymorphic_cast.hpp
main.o: range-v3/include/range/v3/view/bounded.hpp
main.o: range-v3/include/range/v3/view/c_str.hpp
main.o: range-v3/include/range/v3/view/concat.hpp
main.o: range-v3/include/range/v3/view/const.hpp
main.o: range-v3/include/range/v3/view/chunk.hpp
main.o: range-v3/include/range/v3/view/take.hpp
main.o: range-v3/include/range/v3/view/cycle.hpp
main.o: range-v3/include/range/v3/view/drop.hpp
main.o: range-v3/include/range/v3/view/drop_exactly.hpp
main.o: range-v3/include/range/v3/view/drop_while.hpp
main.o: range-v3/include/range/v3/view/empty.hpp
main.o: range-v3/include/range/v3/view/filter.hpp
main.o: range-v3/include/range/v3/view/remove_if.hpp
main.o: range-v3/include/range/v3/view/for_each.hpp
main.o: range-v3/include/range/v3/view/join.hpp
main.o: range-v3/include/range/v3/view/single.hpp
main.o: range-v3/include/range/v3/view/generate_n.hpp
main.o: range-v3/include/range/v3/view/generate.hpp
main.o: range-v3/include/range/v3/view/repeat_n.hpp
main.o: range-v3/include/range/v3/view/group_by.hpp
main.o: range-v3/include/range/v3/view/intersperse.hpp
main.o: range-v3/include/range/v3/view/map.hpp
main.o: range-v3/include/range/v3/view/move.hpp
main.o: range-v3/include/range/v3/view/partial_sum.hpp
main.o: range-v3/include/range/v3/view/repeat.hpp
main.o: range-v3/include/range/v3/view/replace.hpp
main.o: range-v3/include/range/v3/view/replace_if.hpp
main.o: range-v3/include/range/v3/view/reverse.hpp
main.o: range-v3/include/range/v3/view/sample.hpp
main.o: range-v3/include/range/v3/view/set_algorithm.hpp
main.o: range-v3/include/range/v3/view/slice.hpp
main.o: range-v3/include/range/v3/view/sliding.hpp
main.o: range-v3/include/range/v3/view/stride.hpp
main.o: range-v3/include/range/v3/view/tail.hpp
main.o: range-v3/include/range/v3/view/tokenize.hpp
main.o: range-v3/include/range/v3/view/unbounded.hpp
main.o: range-v3/include/range/v3/view/unique.hpp
main.o: range-v3/include/range/v3/view/zip_with.hpp
main.o: range-v3/include/range/v3/view/zip.hpp problem-001.hpp
main.o: problem-002.hpp problem-003.hpp
